Todo branch
Oxford-G/Todo-List pull request #1
Opened 2021-06-26 12:42 UTC by Oxford-G

This project is a javascript-based Todo web application.
 Features include the following
- Filterale todos based on three parameters (All Todos, Pending Todos, Completed Todos).
- User can delete the todos.
- Highlight todos by toggling the checkbox.

2021-06-26 18:37 UTC, Forison requested changes
## Status::Changes required❌

# 👋 @Oxford-G 

#### You have done a good job on this one so far, there is default project, users can read, update, delete todos and projects, and Webpack is well configured🤗 .

Here are some issues to address to get this approved:

* [ ] It uses ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))
- Let us use arrow functions in all our function definitions

* [ ] Let us state explicitly on which port/url to start the application after `npm start`.

* [ ] Do not modify linter configuration, let us remove the comments and try to

**[Optional]**

* [ ] It would be better not to allow the deletion of  default projects, the others however, can be deleted. The default one should be such that we can remove the it `todos` but the project name should always be available.

* [ ] It is always better to capitalize your commit messages.

* [ ] We can improve on the UI with some styling, It could be a good candidate for our future portfolio.

#### That is it kindly make the changes and submit a re-review😎

#### Happy coding😇

Addo Forison

2021-06-26 18:43 UTC, Forison commented on src/project.js
> +// eslint-disable-next-line import/no-cycle
* [ ]  Do not modify linter configurations
Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)))

2021-06-26 18:43 UTC, Forison commented on src/project.js
> +  function createProject(target) {
Let us use arrow functions in function definition.

2021-06-26 18:43 UTC, Forison commented on src/start.js
> +function getProjects() {
Let us use arrow functions in function definition.

2021-06-26 18:43 UTC, Forison commented on src/start.js
> +function clearContent(element) {
Let us use arrow functions in function definition.

2021-06-26 18:43 UTC, Forison commented on src/start.js
> +function displayProjects() {
Let us use arrow functions in function definition.

2021-06-26 18:43 UTC, Forison commented on src/start.js
> +function displayTodoForm() {
Let us use arrow functions in function definition.

2021-06-26 18:43 UTC, Forison commented on src/start.js
> +function displayTodos() {
Let us use arrow functions in function definition.

2021-06-29 15:07 UTC, BrianSammit requested changes
CHANGES REQUIRED 🔴 🛑 
-----------
Hello @Oxford-G, great job you are doing on this project 👏 
However, there is a minor change to make to complete this milestone 🛠️ see it below 👀 👇 
------------------

- [ ] As the previous reviewer asks you to change, use arrow functions instead of the function keyword.  Change all the functions to arrow functions you still have some that did not change. In `inde.js` and `satrt.js` 
------ 
Please make this required change and send it again for another review 💪 👍 
HAPPY CODING!!! 😄 

![kvUU7](https://user-images.githubusercontent.com/64173189/123821912-6e8db300-d8c1-11eb-94a9-1c35c9dc9192.gif)

2021-06-29 16:02 UTC, rukundoeric approved these changes
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 
  - All issues raised from the previous review are addressed. 💯 


- ### To Improve
  - n/a

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/),
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-06-29 18:15 UTC, merged